//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2024-03-13T13:00:13.7282378-07:00
// ----------------------------------------------------------
// 
// 
// 
namespace CaptainCoder.Dungeoneering.Scripting {
    
    
    public abstract class LuaInitializer {
        
        private LuaInitializer() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_c6e2376d50ff460fbb88ddf6730ef873());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_573b5f2a30514c608fa4e1060615135d());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_8e52e0fef6ca43429bf5c7bd3c695e5c());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_f50a596382774492a6e1f5bc3e3f91e2());
        }
        
        #region Descriptor of DungeonCrawler.Lua.LuaAPI
        // Descriptor of DungeonCrawler.Lua.LuaAPI
        private sealed class TYPE_c6e2376d50ff460fbb88ddf6730ef873 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_c6e2376d50ff460fbb88ddf6730ef873() : 
                    base(typeof(DungeonCrawler.Lua.LuaAPI)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(DungeonCrawler.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b446fa390244444fb96b8c03372acbdb()}));
                this.AddMember("Sum", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Sum", typeof(DungeonCrawler.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cb2203b514da4269a86cd1042d14cc9d()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(DungeonCrawler.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cf3762a42eee428db878cbbd818e5248()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(DungeonCrawler.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_957ce9f42bde445abeeaf08eac6b744a()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(DungeonCrawler.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a14bfcb007e84ecfa7ad7c508d9919a6()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(DungeonCrawler.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f6daa7f7864d4963b9e75c4808a4e7a5()}));
            }
            
            private sealed class MTHD_b446fa390244444fb96b8c03372acbdb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b446fa390244444fb96b8c03372acbdb() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new DungeonCrawler.Lua.LuaAPI();
                }
            }
            
            private sealed class MTHD_cb2203b514da4269a86cd1042d14cc9d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cb2203b514da4269a86cd1042d14cc9d() {
                    this.Initialize("Sum", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((DungeonCrawler.Lua.LuaAPI)(obj)).Sum(((int)(pars[0])), ((int)(pars[1])));
                }
            }
            
            private sealed class MTHD_cf3762a42eee428db878cbbd818e5248 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cf3762a42eee428db878cbbd818e5248() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_957ce9f42bde445abeeaf08eac6b744a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_957ce9f42bde445abeeaf08eac6b744a() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_a14bfcb007e84ecfa7ad7c508d9919a6 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a14bfcb007e84ecfa7ad7c508d9919a6() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_f6daa7f7864d4963b9e75c4808a4e7a5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f6daa7f7864d4963b9e75c4808a4e7a5() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of DungeonCrawler.Lua.LuaContext
        // Descriptor of DungeonCrawler.Lua.LuaContext
        private sealed class TYPE_573b5f2a30514c608fa4e1060615135d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_573b5f2a30514c608fa4e1060615135d() : 
                    base(typeof(DungeonCrawler.Lua.LuaContext)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_02ffcbe6387d4b4eab15b804bfd671a9()}));
                this.AddMember("get_PlayerView", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_PlayerView", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c4cb5cd790f244689adddb8b5459ae9d()}));
                this.AddMember("SetPlayerPosition", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerPosition", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2be823f9f3e74187a844bd23cf3ccf67()}));
                this.AddMember("SetPlayerFacing", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerFacing", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4395d3e3dba8476c9f382f5745338e2b()}));
                this.AddMember("SetPlayerView", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerView", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_27086262d1ea44aeb0be556ecf0be81b()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_53877470539d45469b62cb987f11b5c5()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ed9dfe32ac8d4fc6a734dde3e5e9026a()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a29eabf47b09468e948a0bbf40699908()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(DungeonCrawler.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_7e1c8c4f6fac4108a280965949ad502b()}));
                this.AddMember("PlayerView", new PROP_c87d29fca34f4bc78c250768bdb88710());
            }
            
            private sealed class MTHD_02ffcbe6387d4b4eab15b804bfd671a9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_02ffcbe6387d4b4eab15b804bfd671a9() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("context", typeof(DungeonCrawler.Lua.IScriptContext), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new DungeonCrawler.Lua.LuaContext(((DungeonCrawler.Lua.IScriptContext)(pars[0])));
                }
            }
            
            private sealed class MTHD_c4cb5cd790f244689adddb8b5459ae9d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c4cb5cd790f244689adddb8b5459ae9d() {
                    this.Initialize("get_PlayerView", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((DungeonCrawler.Lua.LuaContext)(obj)).PlayerView;
                }
            }
            
            private sealed class MTHD_2be823f9f3e74187a844bd23cf3ccf67 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2be823f9f3e74187a844bd23cf3ccf67() {
                    this.Initialize("SetPlayerPosition", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((DungeonCrawler.Lua.LuaContext)(obj)).SetPlayerPosition(((int)(pars[0])), ((int)(pars[1])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_4395d3e3dba8476c9f382f5745338e2b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_4395d3e3dba8476c9f382f5745338e2b() {
                    this.Initialize("SetPlayerFacing", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("facing", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((DungeonCrawler.Lua.LuaContext)(obj)).SetPlayerFacing(((int)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_27086262d1ea44aeb0be556ecf0be81b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_27086262d1ea44aeb0be556ecf0be81b() {
                    this.Initialize("SetPlayerView", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("facing", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((DungeonCrawler.Lua.LuaContext)(obj)).SetPlayerView(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_53877470539d45469b62cb987f11b5c5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_53877470539d45469b62cb987f11b5c5() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_ed9dfe32ac8d4fc6a734dde3e5e9026a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ed9dfe32ac8d4fc6a734dde3e5e9026a() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_a29eabf47b09468e948a0bbf40699908 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a29eabf47b09468e948a0bbf40699908() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_7e1c8c4f6fac4108a280965949ad502b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_7e1c8c4f6fac4108a280965949ad502b() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_c87d29fca34f4bc78c250768bdb88710 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_c87d29fca34f4bc78c250768bdb88710() : 
                        base(typeof(MoonSharp.Interpreter.DynValue), "PlayerView", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((DungeonCrawler.Lua.LuaContext)(obj)).PlayerView;
                }
            }
        }
        #endregion
        
        #region Descriptor of DungeonCrawler.Lua.PlayerViewProxy
        // Descriptor of DungeonCrawler.Lua.PlayerViewProxy
        private sealed class TYPE_8e52e0fef6ca43429bf5c7bd3c695e5c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_8e52e0fef6ca43429bf5c7bd3c695e5c() : 
                    base(typeof(DungeonCrawler.Lua.PlayerViewProxy)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(DungeonCrawler.Lua.PlayerViewProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f0681548403043809c06f3f2d75dc4d8()}));
                this.AddMember("get_Position", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Position", typeof(DungeonCrawler.Lua.PlayerViewProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_fe44bb0141b94533b3e19b58f7ec8ad4()}));
                this.AddMember("get_Facing", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Facing", typeof(DungeonCrawler.Lua.PlayerViewProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_50425850cb4f4e70bddba298d0d022c8()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(DungeonCrawler.Lua.PlayerViewProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_01f533b5f6cf42a1bf35c78d799c8bb0()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(DungeonCrawler.Lua.PlayerViewProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_03c7d1f2a31548198098ab0794177019()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(DungeonCrawler.Lua.PlayerViewProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9e60c284ad774ff49fc5ce86c8d65135()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(DungeonCrawler.Lua.PlayerViewProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b4fd7d3a72624225bc5bd1f6e1a9a87a()}));
                this.AddMember("Position", new PROP_05e6155a3be04904a1e5d40cd8870105());
                this.AddMember("Facing", new PROP_e43d7b29712242e8a6eefa82f41a9d6d());
            }
            
            private sealed class MTHD_f0681548403043809c06f3f2d75dc4d8 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f0681548403043809c06f3f2d75dc4d8() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(CaptainCoder.Dungeoneering.Player.PlayerView), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new DungeonCrawler.Lua.PlayerViewProxy(((CaptainCoder.Dungeoneering.Player.PlayerView)(pars[0])));
                }
            }
            
            private sealed class MTHD_fe44bb0141b94533b3e19b58f7ec8ad4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_fe44bb0141b94533b3e19b58f7ec8ad4() {
                    this.Initialize("get_Position", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((DungeonCrawler.Lua.PlayerViewProxy)(obj)).Position;
                }
            }
            
            private sealed class MTHD_50425850cb4f4e70bddba298d0d022c8 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_50425850cb4f4e70bddba298d0d022c8() {
                    this.Initialize("get_Facing", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((DungeonCrawler.Lua.PlayerViewProxy)(obj)).Facing;
                }
            }
            
            private sealed class MTHD_01f533b5f6cf42a1bf35c78d799c8bb0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_01f533b5f6cf42a1bf35c78d799c8bb0() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_03c7d1f2a31548198098ab0794177019 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_03c7d1f2a31548198098ab0794177019() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_9e60c284ad774ff49fc5ce86c8d65135 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_9e60c284ad774ff49fc5ce86c8d65135() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_b4fd7d3a72624225bc5bd1f6e1a9a87a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b4fd7d3a72624225bc5bd1f6e1a9a87a() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_05e6155a3be04904a1e5d40cd8870105 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_05e6155a3be04904a1e5d40cd8870105() : 
                        base(typeof(MoonSharp.Interpreter.DynValue), "Position", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((DungeonCrawler.Lua.PlayerViewProxy)(obj)).Position;
                }
            }
            
            private sealed class PROP_e43d7b29712242e8a6eefa82f41a9d6d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_e43d7b29712242e8a6eefa82f41a9d6d() : 
                        base(typeof(int), "Facing", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((DungeonCrawler.Lua.PlayerViewProxy)(obj)).Facing;
                }
            }
        }
        #endregion
        
        #region Descriptor of DungeonCrawler.Lua.PositionProxy
        // Descriptor of DungeonCrawler.Lua.PositionProxy
        private sealed class TYPE_f50a596382774492a6e1f5bc3e3f91e2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_f50a596382774492a6e1f5bc3e3f91e2() : 
                    base(typeof(DungeonCrawler.Lua.PositionProxy)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(DungeonCrawler.Lua.PositionProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_92ad0a1b5b3a4dbab8c3189c021fce27()}));
                this.AddMember("get_X", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_X", typeof(DungeonCrawler.Lua.PositionProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_afe64073c7b84045b6560fc22b1526ec()}));
                this.AddMember("get_Y", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Y", typeof(DungeonCrawler.Lua.PositionProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8038946476f449a79f5068c420ae1190()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(DungeonCrawler.Lua.PositionProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_90b465f35ed14f9c8384dd287b6610b0()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(DungeonCrawler.Lua.PositionProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ec74fe06eb6f42aead76d7007a0c2567()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(DungeonCrawler.Lua.PositionProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_16878baeb11d463bb181055a5b09b5a2()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(DungeonCrawler.Lua.PositionProxy), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8ffe6adc045c4fc89fc44ddb877e1ff0()}));
                this.AddMember("X", new PROP_5de07363603c4970863043dda29daa6e());
                this.AddMember("Y", new PROP_fc29a4cdeead4ca19a57f371fa9baf1d());
            }
            
            private sealed class MTHD_92ad0a1b5b3a4dbab8c3189c021fce27 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_92ad0a1b5b3a4dbab8c3189c021fce27() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(CaptainCoder.Dungeoneering.DungeonMap.Position), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new DungeonCrawler.Lua.PositionProxy(((CaptainCoder.Dungeoneering.DungeonMap.Position)(pars[0])));
                }
            }
            
            private sealed class MTHD_afe64073c7b84045b6560fc22b1526ec : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_afe64073c7b84045b6560fc22b1526ec() {
                    this.Initialize("get_X", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((DungeonCrawler.Lua.PositionProxy)(obj)).X;
                }
            }
            
            private sealed class MTHD_8038946476f449a79f5068c420ae1190 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8038946476f449a79f5068c420ae1190() {
                    this.Initialize("get_Y", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((DungeonCrawler.Lua.PositionProxy)(obj)).Y;
                }
            }
            
            private sealed class MTHD_90b465f35ed14f9c8384dd287b6610b0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_90b465f35ed14f9c8384dd287b6610b0() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_ec74fe06eb6f42aead76d7007a0c2567 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ec74fe06eb6f42aead76d7007a0c2567() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_16878baeb11d463bb181055a5b09b5a2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_16878baeb11d463bb181055a5b09b5a2() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_8ffe6adc045c4fc89fc44ddb877e1ff0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8ffe6adc045c4fc89fc44ddb877e1ff0() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_5de07363603c4970863043dda29daa6e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_5de07363603c4970863043dda29daa6e() : 
                        base(typeof(int), "X", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((DungeonCrawler.Lua.PositionProxy)(obj)).X;
                }
            }
            
            private sealed class PROP_fc29a4cdeead4ca19a57f371fa9baf1d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_fc29a4cdeead4ca19a57f371fa9baf1d() : 
                        base(typeof(int), "Y", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((DungeonCrawler.Lua.PositionProxy)(obj)).Y;
                }
            }
        }
        #endregion
    }
}
