//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2024-03-16T06:44:34.1113682-07:00
// ----------------------------------------------------------
// 
// 
// 
namespace CaptainCoder.Dungeoneering.Lua {
    
    
    public abstract class LuaInitializer {
        
        private LuaInitializer() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_f5cb092bcf88477ea4eec779818792b2());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_52876a6317b444c1ab4ab86d2f5b4745());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_4c472764a8804cb28ab6c2f71f7c2289());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_a8c18e58b8c1498681321ed9b322fe9a());
        }
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.LuaAPI
        // Descriptor of CaptainCoder.Dungeoneering.Lua.LuaAPI
        private sealed class TYPE_f5cb092bcf88477ea4eec779818792b2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_f5cb092bcf88477ea4eec779818792b2() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_73b8590e7680450eb786631ac4a6ce03()}));
                this.AddMember("Sum", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Sum", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_35c4510278564efbbe3a78a09e561d18()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8b6810bdbdec43be983daafa827fd450()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8f6d95056f65488f810598173919f6e7()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_799dd3efc7084093a202553dbc2b84c2()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c234b572302543e698e8dd3de11f1312()}));
            }
            
            private sealed class MTHD_73b8590e7680450eb786631ac4a6ce03 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_73b8590e7680450eb786631ac4a6ce03() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.LuaAPI();
                }
            }
            
            private sealed class MTHD_35c4510278564efbbe3a78a09e561d18 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_35c4510278564efbbe3a78a09e561d18() {
                    this.Initialize("Sum", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaAPI)(obj)).Sum(((int)(pars[0])), ((int)(pars[1])));
                }
            }
            
            private sealed class MTHD_8b6810bdbdec43be983daafa827fd450 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8b6810bdbdec43be983daafa827fd450() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_8f6d95056f65488f810598173919f6e7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8f6d95056f65488f810598173919f6e7() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_799dd3efc7084093a202553dbc2b84c2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_799dd3efc7084093a202553dbc2b84c2() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_c234b572302543e698e8dd3de11f1312 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c234b572302543e698e8dd3de11f1312() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.LuaContext
        // Descriptor of CaptainCoder.Dungeoneering.Lua.LuaContext
        private sealed class TYPE_52876a6317b444c1ab4ab86d2f5b4745 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_52876a6317b444c1ab4ab86d2f5b4745() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.LuaContext)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_75036d232a0d4bbbbf5210cc2385d71d()}));
                this.AddMember("get_PlayerView", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_PlayerView", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f9163153d5054165ab84bb7efd529ea9()}));
                this.AddMember("SetPlayerPosition", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerPosition", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_14fe944268f243f1ab726e766b2f5d7b()}));
                this.AddMember("SetPlayerFacing", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerFacing", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_764b49e52fed41d4b84a0ecdc8494a9b()}));
                this.AddMember("SetPlayerView", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerView", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f5becb9a2e604ca6b78e338b5011317a()}));
                this.AddMember("GetWall", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetWall", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_03237a670e09465aae0f9b830b2f2f41()}));
                this.AddMember("GetWallAt", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetWallAt", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_45aa8969357f4d9da2bb56675f40879c()}));
                this.AddMember("SetWall", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetWall", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_31b2dbb5e7154db09a84397e52599c45()}));
                this.AddMember("SetWallAt", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetWallAt", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e5569ae086f54ce59351fd40c40f04ad()}));
                this.AddMember("WriteInfo", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("WriteInfo", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e99b9042c7374849a113724228c25f98()}));
                this.AddMember("Debug", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Debug", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_89595d58c85a474b80d43e2aaf544a0d()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cf52390ece814472a140be6e67ca0929()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3d78e13abafd45bebb7cc6cbaf9baa7e()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a491293195474f3596db1389e1bfc111()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d6d7ba33c0c744678614606aa1c0980b()}));
                this.AddMember("PlayerView", new PROP_151ce9c767724a328561b8bc080080bb());
            }
            
            private sealed class MTHD_75036d232a0d4bbbbf5210cc2385d71d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_75036d232a0d4bbbbf5210cc2385d71d() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("context", typeof(CaptainCoder.Dungeoneering.DungeonCrawler.Scripting.IScriptContext), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.LuaContext(((CaptainCoder.Dungeoneering.DungeonCrawler.Scripting.IScriptContext)(pars[0])));
                }
            }
            
            private sealed class MTHD_f9163153d5054165ab84bb7efd529ea9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f9163153d5054165ab84bb7efd529ea9() {
                    this.Initialize("get_PlayerView", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).PlayerView;
                }
            }
            
            private sealed class MTHD_14fe944268f243f1ab726e766b2f5d7b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_14fe944268f243f1ab726e766b2f5d7b() {
                    this.Initialize("SetPlayerPosition", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetPlayerPosition(((int)(pars[0])), ((int)(pars[1])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_764b49e52fed41d4b84a0ecdc8494a9b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_764b49e52fed41d4b84a0ecdc8494a9b() {
                    this.Initialize("SetPlayerFacing", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("facing", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetPlayerFacing(((int)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_f5becb9a2e604ca6b78e338b5011317a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f5becb9a2e604ca6b78e338b5011317a() {
                    this.Initialize("SetPlayerView", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("facing", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetPlayerView(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_03237a670e09465aae0f9b830b2f2f41 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_03237a670e09465aae0f9b830b2f2f41() {
                    this.Initialize("GetWall", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).GetWall();
                }
            }
            
            private sealed class MTHD_45aa8969357f4d9da2bb56675f40879c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_45aa8969357f4d9da2bb56675f40879c() {
                    this.Initialize("GetWallAt", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("f", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).GetWallAt(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])));
                }
            }
            
            private sealed class MTHD_31b2dbb5e7154db09a84397e52599c45 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_31b2dbb5e7154db09a84397e52599c45() {
                    this.Initialize("SetWall", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("type", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetWall(((int)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_e5569ae086f54ce59351fd40c40f04ad : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e5569ae086f54ce59351fd40c40f04ad() {
                    this.Initialize("SetWallAt", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("f", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("type", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetWallAt(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])), ((int)(pars[3])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_e99b9042c7374849a113724228c25f98 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e99b9042c7374849a113724228c25f98() {
                    this.Initialize("WriteInfo", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("message", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).WriteInfo(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_89595d58c85a474b80d43e2aaf544a0d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_89595d58c85a474b80d43e2aaf544a0d() {
                    this.Initialize("Debug", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("message", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).Debug(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_cf52390ece814472a140be6e67ca0929 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cf52390ece814472a140be6e67ca0929() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_3d78e13abafd45bebb7cc6cbaf9baa7e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3d78e13abafd45bebb7cc6cbaf9baa7e() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_a491293195474f3596db1389e1bfc111 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a491293195474f3596db1389e1bfc111() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_d6d7ba33c0c744678614606aa1c0980b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d6d7ba33c0c744678614606aa1c0980b() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_151ce9c767724a328561b8bc080080bb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_151ce9c767724a328561b8bc080080bb() : 
                        base(typeof(MoonSharp.Interpreter.DynValue), "PlayerView", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).PlayerView;
                }
            }
        }
        #endregion
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView
        // Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView
        private sealed class TYPE_4c472764a8804cb28ab6c2f71f7c2289 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_4c472764a8804cb28ab6c2f71f7c2289() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_515e14d980774fce87e6c7d465ca7fb1()}));
                this.AddMember("get_Position", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Position", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c9cf1e928e954443895a2881b15366a4()}));
                this.AddMember("get_Facing", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Facing", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3a3727f62b464317a7a1c4be997591bc()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b745868434f0465c8423f660c596c397()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ad43d1c32ba64ee2bfcdb14922f27fce()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a7af35450f3c403b8ca0c67ff67848e3()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_fddcb7a600d54b6a80dbb69d46ec09e4()}));
                this.AddMember("Position", new PROP_f03c132bb9e94762932b64f9758cf480());
                this.AddMember("Facing", new PROP_77b418d633e1403796a36d655e5a8970());
            }
            
            private sealed class MTHD_515e14d980774fce87e6c7d465ca7fb1 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_515e14d980774fce87e6c7d465ca7fb1() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(CaptainCoder.Dungeoneering.Player.PlayerView), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView(((CaptainCoder.Dungeoneering.Player.PlayerView)(pars[0])));
                }
            }
            
            private sealed class MTHD_c9cf1e928e954443895a2881b15366a4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c9cf1e928e954443895a2881b15366a4() {
                    this.Initialize("get_Position", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Position;
                }
            }
            
            private sealed class MTHD_3a3727f62b464317a7a1c4be997591bc : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3a3727f62b464317a7a1c4be997591bc() {
                    this.Initialize("get_Facing", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Facing;
                }
            }
            
            private sealed class MTHD_b745868434f0465c8423f660c596c397 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b745868434f0465c8423f660c596c397() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_ad43d1c32ba64ee2bfcdb14922f27fce : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ad43d1c32ba64ee2bfcdb14922f27fce() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_a7af35450f3c403b8ca0c67ff67848e3 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a7af35450f3c403b8ca0c67ff67848e3() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_fddcb7a600d54b6a80dbb69d46ec09e4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_fddcb7a600d54b6a80dbb69d46ec09e4() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_f03c132bb9e94762932b64f9758cf480 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_f03c132bb9e94762932b64f9758cf480() : 
                        base(typeof(MoonSharp.Interpreter.DynValue), "Position", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Position;
                }
            }
            
            private sealed class PROP_77b418d633e1403796a36d655e5a8970 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_77b418d633e1403796a36d655e5a8970() : 
                        base(typeof(int), "Facing", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Facing;
                }
            }
        }
        #endregion
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.Position
        // Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.Position
        private sealed class TYPE_a8c18e58b8c1498681321ed9b322fe9a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_a8c18e58b8c1498681321ed9b322fe9a() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a94c6fdf748f427ea3788f7a27cd3b52()}));
                this.AddMember("get_X", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_X", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d83929f1144446308e978a463f1fc527()}));
                this.AddMember("get_Y", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Y", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1fb7d250cb224991b1bc943b04cb1d10()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_478cddf36e6444f4880bbb611804dc0e()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a50491075ce74a85b2bcad1219c4c87f()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4526d1482460413c9cde9ecc0847e8f7()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_efd096f08f3d4c648f5d93fb6f382bcd()}));
                this.AddMember("X", new PROP_8dba6cc317f34a8ca3ce03a3e2ce033b());
                this.AddMember("Y", new PROP_00ad4bf7f8b14ae8b3a1ceb571664611());
            }
            
            private sealed class MTHD_a94c6fdf748f427ea3788f7a27cd3b52 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a94c6fdf748f427ea3788f7a27cd3b52() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(CaptainCoder.Dungeoneering.DungeonMap.Position), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.Proxy.Position(((CaptainCoder.Dungeoneering.DungeonMap.Position)(pars[0])));
                }
            }
            
            private sealed class MTHD_d83929f1144446308e978a463f1fc527 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d83929f1144446308e978a463f1fc527() {
                    this.Initialize("get_X", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).X;
                }
            }
            
            private sealed class MTHD_1fb7d250cb224991b1bc943b04cb1d10 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1fb7d250cb224991b1bc943b04cb1d10() {
                    this.Initialize("get_Y", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).Y;
                }
            }
            
            private sealed class MTHD_478cddf36e6444f4880bbb611804dc0e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_478cddf36e6444f4880bbb611804dc0e() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_a50491075ce74a85b2bcad1219c4c87f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a50491075ce74a85b2bcad1219c4c87f() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_4526d1482460413c9cde9ecc0847e8f7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_4526d1482460413c9cde9ecc0847e8f7() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_efd096f08f3d4c648f5d93fb6f382bcd : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_efd096f08f3d4c648f5d93fb6f382bcd() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_8dba6cc317f34a8ca3ce03a3e2ce033b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_8dba6cc317f34a8ca3ce03a3e2ce033b() : 
                        base(typeof(int), "X", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).X;
                }
            }
            
            private sealed class PROP_00ad4bf7f8b14ae8b3a1ceb571664611 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_00ad4bf7f8b14ae8b3a1ceb571664611() : 
                        base(typeof(int), "Y", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).Y;
                }
            }
        }
        #endregion
    }
}
