//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2024-03-21T05:42:57.4300903-07:00
// ----------------------------------------------------------
// 
// 
// 
namespace CaptainCoder.Dungeoneering.Lua {
    
    
    public abstract class LuaInitializer {
        
        private LuaInitializer() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_4d10f093c23d4c938c8c601b3a0e8992());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_42968904b7594a3c90a9a8cbec719d5a());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_a4e3e462763a40e090ce733ec9b7d969());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_7e1c26d826fc41a19e770f68bb095a79());
        }
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.LuaAPI
        // Descriptor of CaptainCoder.Dungeoneering.Lua.LuaAPI
        private sealed class TYPE_4d10f093c23d4c938c8c601b3a0e8992 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_4d10f093c23d4c938c8c601b3a0e8992() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_919cdb370db0468b990129fbbb55b910()}));
                this.AddMember("Sum", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Sum", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c641db7443d345d2b1f07f887a76a549()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_0384e37bae3c46609f19a6d61d07b1a2()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_6ae5c0c112f641d4a98619944bd8a598()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c136377c84004077bc05434595a6e321()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.LuaAPI), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cf05eb9f28e04e9ca656f8d2860de323()}));
            }
            
            private sealed class MTHD_919cdb370db0468b990129fbbb55b910 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_919cdb370db0468b990129fbbb55b910() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.LuaAPI();
                }
            }
            
            private sealed class MTHD_c641db7443d345d2b1f07f887a76a549 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c641db7443d345d2b1f07f887a76a549() {
                    this.Initialize("Sum", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaAPI)(obj)).Sum(((int)(pars[0])), ((int)(pars[1])));
                }
            }
            
            private sealed class MTHD_0384e37bae3c46609f19a6d61d07b1a2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_0384e37bae3c46609f19a6d61d07b1a2() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_6ae5c0c112f641d4a98619944bd8a598 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_6ae5c0c112f641d4a98619944bd8a598() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_c136377c84004077bc05434595a6e321 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c136377c84004077bc05434595a6e321() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_cf05eb9f28e04e9ca656f8d2860de323 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cf05eb9f28e04e9ca656f8d2860de323() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.LuaContext
        // Descriptor of CaptainCoder.Dungeoneering.Lua.LuaContext
        private sealed class TYPE_42968904b7594a3c90a9a8cbec719d5a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_42968904b7594a3c90a9a8cbec719d5a() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.LuaContext)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_59d18ca729a240239cf1e47c50c5262d()}));
                this.AddMember("get_LoadFromURL", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_LoadFromURL", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_179adf73fc8845f5813311d49de3d218()}));
                this.AddMember("set_LoadFromURL", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("set_LoadFromURL", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b00efc768e1649668e2fee64659a8b1c()}));
                this.AddMember("get_PlayerView", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_PlayerView", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e28a8a5537b1451eba30d56dd92ce5fd()}));
                this.AddMember("SetPlayerPosition", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerPosition", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_817699a15a69473db697290ea7166886()}));
                this.AddMember("SetPlayerFacing", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerFacing", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_091a260f4c3b4574b8b0e0d5f2b4fe8f()}));
                this.AddMember("SetPlayerView", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayerView", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_bf390e872d564768b0acff923d9fc097()}));
                this.AddMember("GetWall", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetWall", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_6be7c09d0ed949ad8f0e2972c1489af8()}));
                this.AddMember("GetWallAt", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetWallAt", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c294d78a4418475aba56f8aef1d7146b()}));
                this.AddMember("SetWall", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetWall", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_6e0523a760d14f7095b04e2f70723ee4()}));
                this.AddMember("SetWallAt", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetWallAt", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2f81e30d0b3e4a2385113326a730be6f()}));
                this.AddMember("SetWallTexture", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetWallTexture", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_46960ccabf84452185eba4bdba832541()}));
                this.AddMember("SetVariable", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetVariable", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_afb849eeb9934e6283e6776f12e78175()}));
                this.AddMember("GetVariable", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetVariable", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a65b99de51cf4ea28665fd943e0b0afe()}));
                this.AddMember("WriteInfo", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("WriteInfo", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_497e48dc6bfb4bb9861a7f507a2ffae3()}));
                this.AddMember("Debug", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Debug", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_12296184b2bb4781831d6463321d7c9a()}));
                this.AddMember("ChangeDungeon", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ChangeDungeon", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_918ccbe1ef8f4f1c8d7e5138950c0026()}));
                this.AddMember("LoadCrawlerFromURL", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("LoadCrawlerFromURL", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1c825acfa42640be952820baa288c4a2()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_bcafba20e572410e83cb784299d5696e()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d29c747121dc4f588a9c005a6298d8a7()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_82696d0cc04b42ad92740a8ae3267e67()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.LuaContext), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_08f6c12ddb1f43c6984ea08d9bcae0de()}));
                this.AddMember("LoadFromURL", new PROP_84f2c78951c4468ea32a6a849d802ec4());
                this.AddMember("PlayerView", new PROP_e83996fec90842c6832787cd16185467());
            }
            
            private sealed class MTHD_59d18ca729a240239cf1e47c50c5262d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_59d18ca729a240239cf1e47c50c5262d() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("context", typeof(CaptainCoder.Dungeoneering.DungeonCrawler.Scripting.IScriptContext), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.LuaContext(((CaptainCoder.Dungeoneering.DungeonCrawler.Scripting.IScriptContext)(pars[0])));
                }
            }
            
            private sealed class MTHD_179adf73fc8845f5813311d49de3d218 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_179adf73fc8845f5813311d49de3d218() {
                    this.Initialize("get_LoadFromURL", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return CaptainCoder.Dungeoneering.Lua.LuaContext.LoadFromURL;
                }
            }
            
            private sealed class MTHD_b00efc768e1649668e2fee64659a8b1c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b00efc768e1649668e2fee64659a8b1c() {
                    this.Initialize("set_LoadFromURL", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(System.Action<string>), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    CaptainCoder.Dungeoneering.Lua.LuaContext.LoadFromURL = ((System.Action<string>)(pars[0]));
                    return null;
                }
            }
            
            private sealed class MTHD_e28a8a5537b1451eba30d56dd92ce5fd : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e28a8a5537b1451eba30d56dd92ce5fd() {
                    this.Initialize("get_PlayerView", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).PlayerView;
                }
            }
            
            private sealed class MTHD_817699a15a69473db697290ea7166886 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_817699a15a69473db697290ea7166886() {
                    this.Initialize("SetPlayerPosition", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetPlayerPosition(((int)(pars[0])), ((int)(pars[1])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_091a260f4c3b4574b8b0e0d5f2b4fe8f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_091a260f4c3b4574b8b0e0d5f2b4fe8f() {
                    this.Initialize("SetPlayerFacing", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("facing", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetPlayerFacing(((int)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_bf390e872d564768b0acff923d9fc097 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_bf390e872d564768b0acff923d9fc097() {
                    this.Initialize("SetPlayerView", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("facing", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetPlayerView(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_6be7c09d0ed949ad8f0e2972c1489af8 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_6be7c09d0ed949ad8f0e2972c1489af8() {
                    this.Initialize("GetWall", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).GetWall();
                }
            }
            
            private sealed class MTHD_c294d78a4418475aba56f8aef1d7146b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c294d78a4418475aba56f8aef1d7146b() {
                    this.Initialize("GetWallAt", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("f", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).GetWallAt(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])));
                }
            }
            
            private sealed class MTHD_6e0523a760d14f7095b04e2f70723ee4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_6e0523a760d14f7095b04e2f70723ee4() {
                    this.Initialize("SetWall", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("type", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetWall(((int)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_2f81e30d0b3e4a2385113326a730be6f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2f81e30d0b3e4a2385113326a730be6f() {
                    this.Initialize("SetWallAt", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("f", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("type", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetWallAt(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])), ((int)(pars[3])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_46960ccabf84452185eba4bdba832541 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_46960ccabf84452185eba4bdba832541() {
                    this.Initialize("SetWallTexture", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("texture", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetWallTexture(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_afb849eeb9934e6283e6776f12e78175 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_afb849eeb9934e6283e6776f12e78175() {
                    this.Initialize("SetVariable", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("name", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(MoonSharp.Interpreter.DynValue), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).SetVariable(((string)(pars[0])), ((MoonSharp.Interpreter.DynValue)(pars[1])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_a65b99de51cf4ea28665fd943e0b0afe : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a65b99de51cf4ea28665fd943e0b0afe() {
                    this.Initialize("GetVariable", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("name", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).GetVariable(((string)(pars[0])));
                }
            }
            
            private sealed class MTHD_497e48dc6bfb4bb9861a7f507a2ffae3 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_497e48dc6bfb4bb9861a7f507a2ffae3() {
                    this.Initialize("WriteInfo", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("message", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).WriteInfo(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_12296184b2bb4781831d6463321d7c9a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_12296184b2bb4781831d6463321d7c9a() {
                    this.Initialize("Debug", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("message", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).Debug(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_918ccbe1ef8f4f1c8d7e5138950c0026 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_918ccbe1ef8f4f1c8d7e5138950c0026() {
                    this.Initialize("ChangeDungeon", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("dungeonName", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("x", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("y", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("facing", typeof(CaptainCoder.Dungeoneering.DungeonMap.Facing), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).ChangeDungeon(((string)(pars[0])), ((int)(pars[1])), ((int)(pars[2])), ((CaptainCoder.Dungeoneering.DungeonMap.Facing)(pars[3])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_1c825acfa42640be952820baa288c4a2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1c825acfa42640be952820baa288c4a2() {
                    this.Initialize("LoadCrawlerFromURL", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("url", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).LoadCrawlerFromURL(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_bcafba20e572410e83cb784299d5696e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_bcafba20e572410e83cb784299d5696e() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_d29c747121dc4f588a9c005a6298d8a7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d29c747121dc4f588a9c005a6298d8a7() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_82696d0cc04b42ad92740a8ae3267e67 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_82696d0cc04b42ad92740a8ae3267e67() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_08f6c12ddb1f43c6984ea08d9bcae0de : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_08f6c12ddb1f43c6984ea08d9bcae0de() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_84f2c78951c4468ea32a6a849d802ec4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_84f2c78951c4468ea32a6a849d802ec4() : 
                        base(typeof(System.Action<string>), "LoadFromURL", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(3))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return CaptainCoder.Dungeoneering.Lua.LuaContext.LoadFromURL;
                }
                
                protected override void SetValueImpl(MoonSharp.Interpreter.Script script, object obj, object value) {
                    CaptainCoder.Dungeoneering.Lua.LuaContext.LoadFromURL = ((System.Action<string>)(value));
                }
            }
            
            private sealed class PROP_e83996fec90842c6832787cd16185467 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_e83996fec90842c6832787cd16185467() : 
                        base(typeof(MoonSharp.Interpreter.DynValue), "PlayerView", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.LuaContext)(obj)).PlayerView;
                }
            }
        }
        #endregion
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView
        // Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView
        private sealed class TYPE_a4e3e462763a40e090ce733ec9b7d969 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_a4e3e462763a40e090ce733ec9b7d969() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9a205273deb142adb127f3d297c27eaf()}));
                this.AddMember("get_Position", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Position", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c000e33b7e324d4ea032f5666a59eff9()}));
                this.AddMember("get_Facing", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Facing", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5cd9207a72674259b93e04942c769a7b()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4e937e5769ae4aeaa5f4a94a529a13e0()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b09581cd036d42d9a595dfb07f285e73()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1d69a8584a53496f8a66f06bfd08c21c()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_049708aa74b64f5787a87160fe4ec5bd()}));
                this.AddMember("Position", new PROP_009c8d77b40242989ad73742bb4d864a());
                this.AddMember("Facing", new PROP_c7e649b0967f439fbaae2a9f0efd64e6());
            }
            
            private sealed class MTHD_9a205273deb142adb127f3d297c27eaf : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_9a205273deb142adb127f3d297c27eaf() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(CaptainCoder.Dungeoneering.Player.PlayerView), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView(((CaptainCoder.Dungeoneering.Player.PlayerView)(pars[0])));
                }
            }
            
            private sealed class MTHD_c000e33b7e324d4ea032f5666a59eff9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c000e33b7e324d4ea032f5666a59eff9() {
                    this.Initialize("get_Position", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Position;
                }
            }
            
            private sealed class MTHD_5cd9207a72674259b93e04942c769a7b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_5cd9207a72674259b93e04942c769a7b() {
                    this.Initialize("get_Facing", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Facing;
                }
            }
            
            private sealed class MTHD_4e937e5769ae4aeaa5f4a94a529a13e0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_4e937e5769ae4aeaa5f4a94a529a13e0() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_b09581cd036d42d9a595dfb07f285e73 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b09581cd036d42d9a595dfb07f285e73() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_1d69a8584a53496f8a66f06bfd08c21c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1d69a8584a53496f8a66f06bfd08c21c() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_049708aa74b64f5787a87160fe4ec5bd : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_049708aa74b64f5787a87160fe4ec5bd() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_009c8d77b40242989ad73742bb4d864a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_009c8d77b40242989ad73742bb4d864a() : 
                        base(typeof(MoonSharp.Interpreter.DynValue), "Position", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Position;
                }
            }
            
            private sealed class PROP_c7e649b0967f439fbaae2a9f0efd64e6 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_c7e649b0967f439fbaae2a9f0efd64e6() : 
                        base(typeof(int), "Facing", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.PlayerView)(obj)).Facing;
                }
            }
        }
        #endregion
        
        #region Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.Position
        // Descriptor of CaptainCoder.Dungeoneering.Lua.Proxy.Position
        private sealed class TYPE_7e1c26d826fc41a19e770f68bb095a79 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_7e1c26d826fc41a19e770f68bb095a79() : 
                    base(typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9475fffc7eb2429985211754b693ef47()}));
                this.AddMember("get_X", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_X", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_57cb7d38dd4348bbb735262694ecae6e()}));
                this.AddMember("get_Y", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Y", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cf78d58f03e44de18b49028f122b854b()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e15052312cbe44f1838126b60de85115()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_69e71929c35e4b19923f1af69962e66a()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_114bc41aa8b14efa810367ca7aa14bfc()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(CaptainCoder.Dungeoneering.Lua.Proxy.Position), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_274771b9f7994ff7985a89d7863c4254()}));
                this.AddMember("X", new PROP_1773a21d4bfe4ae7b72fa8406997c51e());
                this.AddMember("Y", new PROP_6a635d4d64754d8ead9e49f41455f09d());
            }
            
            private sealed class MTHD_9475fffc7eb2429985211754b693ef47 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_9475fffc7eb2429985211754b693ef47() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(CaptainCoder.Dungeoneering.DungeonMap.Position), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new CaptainCoder.Dungeoneering.Lua.Proxy.Position(((CaptainCoder.Dungeoneering.DungeonMap.Position)(pars[0])));
                }
            }
            
            private sealed class MTHD_57cb7d38dd4348bbb735262694ecae6e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_57cb7d38dd4348bbb735262694ecae6e() {
                    this.Initialize("get_X", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).X;
                }
            }
            
            private sealed class MTHD_cf78d58f03e44de18b49028f122b854b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cf78d58f03e44de18b49028f122b854b() {
                    this.Initialize("get_Y", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).Y;
                }
            }
            
            private sealed class MTHD_e15052312cbe44f1838126b60de85115 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e15052312cbe44f1838126b60de85115() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_69e71929c35e4b19923f1af69962e66a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_69e71929c35e4b19923f1af69962e66a() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_114bc41aa8b14efa810367ca7aa14bfc : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_114bc41aa8b14efa810367ca7aa14bfc() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_274771b9f7994ff7985a89d7863c4254 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_274771b9f7994ff7985a89d7863c4254() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
            
            private sealed class PROP_1773a21d4bfe4ae7b72fa8406997c51e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_1773a21d4bfe4ae7b72fa8406997c51e() : 
                        base(typeof(int), "X", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).X;
                }
            }
            
            private sealed class PROP_6a635d4d64754d8ead9e49f41455f09d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor {
                
                internal PROP_6a635d4d64754d8ead9e49f41455f09d() : 
                        base(typeof(int), "Y", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1))) {
                }
                
                protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj) {
                    return ((CaptainCoder.Dungeoneering.Lua.Proxy.Position)(obj)).Y;
                }
            }
        }
        #endregion
    }
}
