${
	["MoonSharp.Interpreter.Interop.AnonWrapper"] = ${
		skip = true,
	},
	["MoonSharp.Interpreter.Serialization.Json.JsonNull"] = ${
		skip = true,
	},
	["DungeonCrawler.Lua.LuaAPI"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "DungeonCrawler.Lua.LuaAPI",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "DungeonCrawler.Lua.LuaAPI",
						decltype = "DungeonCrawler.Lua.LuaAPI",
						static = true,
						extension = false,
						params = ${ },
					},
				},
			},
			Sum = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Sum",
				decltype = "DungeonCrawler.Lua.LuaAPI",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Sum",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "DungeonCrawler.Lua.LuaAPI",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "x",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[2] = ${
								name = "y",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "DungeonCrawler.Lua.LuaAPI",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "DungeonCrawler.Lua.LuaAPI",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "DungeonCrawler.Lua.LuaAPI",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "DungeonCrawler.Lua.LuaAPI",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
	["DungeonCrawler.Lua.LuaContext"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "DungeonCrawler.Lua.LuaContext",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "context",
								type = "DungeonCrawler.Lua.IScriptContext",
								origtype = "DungeonCrawler.Lua.IScriptContext",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			get_PlayerView = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "get_PlayerView",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "get_PlayerView",
						ctor = false,
						special = true,
						visibility = "public",
						ret = "MoonSharp.Interpreter.DynValue",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			SetPlayerPosition = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetPlayerPosition",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetPlayerPosition",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "x",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[2] = ${
								name = "y",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetPlayerFacing = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetPlayerFacing",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetPlayerFacing",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "facing",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetPlayerView = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetPlayerView",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetPlayerView",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "x",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[2] = ${
								name = "y",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[3] = ${
								name = "facing",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetWall = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetWall",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetWall",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			GetWallAt = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetWallAt",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetWallAt",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "x",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[2] = ${
								name = "y",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[3] = ${
								name = "f",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetWall = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetWall",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetWall",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "type",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetWallAt = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetWallAt",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetWallAt",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "x",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[2] = ${
								name = "y",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[3] = ${
								name = "f",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
							[4] = ${
								name = "type",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			WriteInfo = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "WriteInfo",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "WriteInfo",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "message",
								type = "System.String",
								origtype = "System.String",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			Debug = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Debug",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Debug",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "DungeonCrawler.Lua.LuaContext",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "message",
								type = "System.String",
								origtype = "System.String",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "DungeonCrawler.Lua.LuaContext",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			PlayerView = ${
				class = "MoonSharp.Interpreter.Interop.PropertyMemberDescriptor",
				visibility = "public",
				name = "PlayerView",
				static = false,
				read = true,
				write = false,
				decltype = "DungeonCrawler.Lua.LuaContext",
				declvtype = false,
				type = "MoonSharp.Interpreter.DynValue",
			},
		},
		metamembers = ${ },
	},
	["DungeonCrawler.Lua.Proxy.PlayerView"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "DungeonCrawler.Lua.Proxy.PlayerView",
						decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "target",
								type = "CaptainCoder.Dungeoneering.Player.PlayerView",
								origtype = "CaptainCoder.Dungeoneering.Player.PlayerView",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			get_Position = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "get_Position",
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "get_Position",
						ctor = false,
						special = true,
						visibility = "public",
						ret = "MoonSharp.Interpreter.DynValue",
						decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			get_Facing = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "get_Facing",
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "get_Facing",
						ctor = false,
						special = true,
						visibility = "public",
						ret = "System.Int32",
						decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Position = ${
				class = "MoonSharp.Interpreter.Interop.PropertyMemberDescriptor",
				visibility = "public",
				name = "Position",
				static = false,
				read = true,
				write = false,
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				declvtype = false,
				type = "MoonSharp.Interpreter.DynValue",
			},
			Facing = ${
				class = "MoonSharp.Interpreter.Interop.PropertyMemberDescriptor",
				visibility = "public",
				name = "Facing",
				static = false,
				read = true,
				write = false,
				decltype = "DungeonCrawler.Lua.Proxy.PlayerView",
				declvtype = false,
				type = "System.Int32",
			},
		},
		metamembers = ${ },
	},
	["DungeonCrawler.Lua.Proxy.Position"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "DungeonCrawler.Lua.Proxy.Position",
						decltype = "DungeonCrawler.Lua.Proxy.Position",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "target",
								type = "CaptainCoder.Dungeoneering.DungeonMap.Position",
								origtype = "CaptainCoder.Dungeoneering.DungeonMap.Position",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			get_X = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "get_X",
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "get_X",
						ctor = false,
						special = true,
						visibility = "public",
						ret = "System.Int32",
						decltype = "DungeonCrawler.Lua.Proxy.Position",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			get_Y = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "get_Y",
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "get_Y",
						ctor = false,
						special = true,
						visibility = "public",
						ret = "System.Int32",
						decltype = "DungeonCrawler.Lua.Proxy.Position",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "DungeonCrawler.Lua.Proxy.Position",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			X = ${
				class = "MoonSharp.Interpreter.Interop.PropertyMemberDescriptor",
				visibility = "public",
				name = "X",
				static = false,
				read = true,
				write = false,
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				declvtype = false,
				type = "System.Int32",
			},
			Y = ${
				class = "MoonSharp.Interpreter.Interop.PropertyMemberDescriptor",
				visibility = "public",
				name = "Y",
				static = false,
				read = true,
				write = false,
				decltype = "DungeonCrawler.Lua.Proxy.Position",
				declvtype = false,
				type = "System.Int32",
			},
		},
		metamembers = ${ },
	},
}
