local dialogue = Dialogue([[You are standing in a small closet filled with skeletons]])
dialogue.AddOption(RunScriptDialogueOption("Fight!", "fight-skeletons.lua"))
dialogue.AddOption(RunScriptDialogueOption("Learn Combat Basic", "explain-combat.lua"))
dialogue.AddOption(RunScriptDialogueOption("Leave", "push-back.lua"))
context.ShowDialogue(dialogue)