-- context.ChangeDungeon("Ikea", 11, 11, West)

context.RunScript("begin-quest.lua")
context.AddPartyMember(1)
context.RemovePartyMember(3)
context.RemovePartyMember(2)
context.SetPlayerView(13,21, North)
context.SetVariable("has-green-key", true)
context.SetVariable("has-purple-key", true)
context.SetVariable("defeated-green-room.lua", true)