context.ChangeDungeon("Ikea", 11, 11, West)

-- context.RunScript("begin-quest.lua")
-- context.AddPartyMember(1)
-- context.AddPartyMember(2)
-- context.AddPartyMember(3)
-- context.SetPlayerView(8,4, East)
-- context.SetVariable("has-green-key", true)
-- context.SetVariable("has-purple-key", true)
-- context.SetVariable("has-blue-key", true)
-- context.SetVariable("final-0", true)
-- context.SetVariable("final-1", true)
-- context.SetVariable("final-2", true)
-- context.SetVariable("final-3", true)
-- context.SetVariable("defeated-green-room.lua", true)